#!/bin/bash

echo "🌐 Setting up Resource Pack Auto-Download"
echo ""
echo "📦 Your resource pack: CustomItems4MC-ResourcePack.zip"
echo "🔑 SHA1 Hash: 4514f778c8b44927707b6a578c11a06d302f0be3"
echo ""
echo "🎯 Steps to enable auto-download:"
echo ""
echo "1. Upload CustomItems4MC-ResourcePack.zip to a web server:"
echo "   - GitHub: Create repo, upload file, get direct link"
echo "   - Your server: Upload to public web directory"
echo ""
echo "2. Add to your server.properties:"
echo "   resource-pack=YOUR_URL_HERE"
echo "   resource-pack-sha1=4514f778c8b44927707b6a578c11a06d302f0be3"
echo "   require-resource-pack=true"
echo ""
echo "3. Restart your Paper server"
echo ""
echo "✨ Players will now be prompted to download the pack when they join!"
echo ""
echo "📍 Your Paper server config is at:"
echo "   /home/dev/paper-mc/server.properties"
